name: inright
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  animated_notch_bottom_bar: ^1.0.3
  shared_preferences: ^2.5.2
  fl_chart: ^0.66.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.17.1
  firebase_storage: ^11.6.0
  flutter_local_notifications: ^17.1.0
  awesome_snackbar_content: ^0.1.5
  image_picker: ^1.0.4
  provider: ^6.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
