name: inright
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  animated_notch_bottom_bar: ^1.0.3
  shared_preferences: ^2.5.2
  fl_chart: ^0.66.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  flutter_local_notifications: ^19.2.1
  awesome_snackbar_content: ^0.1.5
  image_picker: ^1.0.4
  provider: ^6.0.5
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_email_sender: ^6.0.0
  url_launcher: ^6.1.10
  vibration: ^3.1.3
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
