// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGvaxHHtvNEZGEa0y6mMzll33tocOir0E',
    appId: '1:1006869933081:web:c70462316eae9cd9018e88',
    messagingSenderId: '1006869933081',
    projectId: 'inrangel',
    authDomain: 'inrangel.firebaseapp.com',
    storageBucket: 'inrangel.firebasestorage.app',
    measurementId: 'G-H73YL3Z6GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmKDTsxohzu7jm8CUJWORJ-BaLUBP-yU8',
    appId: '1:1006869933081:android:aa6a4c93b2769c18018e88',
    messagingSenderId: '1006869933081',
    projectId: 'inrangel',
    storageBucket: 'inrangel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYjM3dzLHsnk9SAnqkUZkhWZnhEKipxsk',
    appId: '1:1006869933081:ios:9920cae5f0d94f17018e88',
    messagingSenderId: '1006869933081',
    projectId: 'inrangel',
    storageBucket: 'inrangel.firebasestorage.app',
    iosBundleId: 'com.example.inright',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYjM3dzLHsnk9SAnqkUZkhWZnhEKipxsk',
    appId: '1:1006869933081:ios:9920cae5f0d94f17018e88',
    messagingSenderId: '1006869933081',
    projectId: 'inrangel',
    storageBucket: 'inrangel.firebasestorage.app',
    iosBundleId: 'com.example.inright',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGvaxHHtvNEZGEa0y6mMzll33tocOir0E',
    appId: '1:1006869933081:web:0b2d80be37963650018e88',
    messagingSenderId: '1006869933081',
    projectId: 'inrangel',
    authDomain: 'inrangel.firebaseapp.com',
    storageBucket: 'inrangel.firebasestorage.app',
    measurementId: 'G-7V22QXCW50',
  );

}